export const fortunes = [
  "💌 Surprise! This cookie carries 100 invisible hugs for you.",
  "💖 Even across miles, my heart is holding yours gently today.",
  "🌞 A small smile will sneak into your day today, courtesy of me.",
  "🌙 No matter how tiring the world gets, you will always be my calm moonlight.",
  "🌼 Your kindness plants flowers even in places you cannot see.",
  "🍫 Just like chocolate, life feels sweeter with you in it.",
  "🌸 You are stronger than you feel, softer than you show, and more loved than you know.",
  "🌸 Your laugh is my favorite melody — I’m humming it today.",
  "🌈 Storms pass, love remains — and I’ll always stay with you.",
  "✨ You make ordinary days glow with extraordinary warmth.",
  "🐚 Like the ocean, you’re deep, beautiful, and endlessly fascinating.",
  "☁️ No matter how heavy today feels, my arms are always your shelter.",
  "🦋 You are still becoming, and that’s such a beautiful thing.",
  "🌻 Sunflowers turn to the sun, and I turn to you.",
  "🌙 Every night, the stars whisper: “she is loved.”",
  "🎶 If today had a soundtrack, it would be your laugh on repeat.",
  "🕊️ Peace finds you when you slow down — and I’ll remind you always.",
  "🍵 Take a sip, breathe deep. You deserve rest, my love.",
  "🌸 Distance is just geography. My love is always beside you.",
  "🔮 Your future is brighter than you can even imagine now.",
  "🌺 You are my favorite hello and my hardest goodbye.",
  "🌈 Rainy days end. Sunshine is already on its way to you.",
  "🐾 If I could, I’d leave little love notes on your path all day.",
  "💖 Patience, darling. The best chapters of your story are yet to unfold.",
  "🌟 Today’s magic is hidden in small, quiet moments. Keep your heart open.",
  "🍪 A cookie can’t hold all my love, but here’s a tiny crumb of it today.",
  "🦋 You are not behind. You are right on time, blooming beautifully.",
  "🌸 You deserve softness, tenderness, and all the love I carry for you.",
  "🌞 Today is lighter because you’re in the world.",
  "💌 Here’s to another month of loving you from near or far."
]
